spring.application.name=my-ai-app
server.port=8888
spring.config.import=optional:file:.env.properties

bailian.api.url=${bailian.api.url}
bailian.api.key=${bailian.api.key}
bailian.api.model=qwen-plus
bailian.api.max-tokens=512