spring.application.name=my-ai-app
server.port=8888
spring.config.import=optional:file:.env.properties

bailian.api.url=${bailian.api.url}
bailian.api.key=${bailian.api.key}
bailian.api.model=${bailian.api.model}
bailian.api.max-tokens=${bailian.api.max-tokens}

spring.datasource.url=${spring.datasource.url}
spring.datasource.username=${spring.datasource.username}
spring.datasource.password=${spring.datasource.password}
spring.datasource.driver-class-name=${spring.datasource.driver-class-name:com.mysql.cj.jdbc.Driver}

mybatis.mapper-locations=classpath:mapper/**/*.xml
mybatis.type-aliases-package=com.ai.app.chat.domain
mybatis.configuration.map-underscore-to-camel-case=true